# Generated by Django 4.0.3 on 2022-04-03 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(default=datetime.datetime(2022, 4, 3, 10, 34, 55, 610890))),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(default=datetime.datetime(2022, 4, 3, 10, 34, 55, 594734))),
            ],
        ),
    ]
