# Generated by Django 4.0.3 on 2022-04-03 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('callresp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 19, 16, 30, 608851, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 19, 16, 30, 582085, tzinfo=utc)),
        ),
    ]
